# Generated by Django 4.2.2 on 2023-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_description",
            field=models.CharField(default="", max_length=128),
        ),
    ]
