# Generated by Django 4.2.2 on 2023-07-18 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(2008, 7, 21, 9, 44, 39, 87214),
                    )
                ),
                name="check_birth_date",
            ),
        ),
    ]
