# Generated by Django 4.2.2 on 2023-07-18 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_options_alter_user_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="check_birth_date",
        ),
        migrations.AddField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(2008, 7, 21, 10, 58, 29, 957400),
                    )
                ),
                name="check_birth_date",
            ),
        ),
    ]
