# Generated by Django 4.2.2 on 2023-07-18 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_check_birth_date_user_can_be_contacted_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="check_birth_date",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birth_date__lte",
                        datetime.datetime(2008, 7, 21, 12, 12, 18, 963360),
                    )
                ),
                name="check_birth_date",
            ),
        ),
    ]
