# Generated by Django 4.2.2 on 2023-07-17 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0002_project_author_alter_project_contributors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="permission",
        ),
    ]
