# Generated by Django 4.2.2 on 2023-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0003_remove_contributor_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contributor",
            name="created_time",
            field=models.DateTimeField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="contributor",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_time",
            field=models.DateTimeField(default="1970-01-01"),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_time",
            field=models.DateTimeField(default="1970-01-01"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(default="1970-01-01"),
        ),
    ]
