# Generated by Django 4.2.2 on 2023-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0004_comment_updated_time_contributor_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
